---
- name: full-config
  image: debian
  command:
    - echo
    - CONFIGMAP_SAMPLE:$(CONFIGMAP_SAMPLE) SECRET_SAMPLE:$(SECRET_SAMPLE) MSG:$(MSG)
  configmap: sample-configmap
  secret: sample-secret
- name: simple-config
  image: debian
  command:
    - echo
    - CONFIGMAP_SAMPLE:$(CONFIGMAP_SAMPLE) SECRET_SAMPLE:$(SECRET_SAMPLE) MSG:$(MSG)
# - name: error config # invalid DNS-1123
#   image: debian
#   command:
#     - echo
#     - CONFIGMAP_SAMPLE:$(CONFIGMAP_SAMPLE) SECRET_SAMPLE:$(SECRET_SAMPLE) MSG:$(MSG)